### Register
POST https://web-production-af7ae.up.railway.app/api/register
Content-Type: application/json

{
  "email": "newuser@example.com",
"password": "password1234",
"name": "Test User"
}

### Login
POST https://web-production-af7ae.up.railway.app/api/login
Content-Type: application/json

{
   "email": "newuser@example.com",
"password": "password1234",
}

### Health
GET https://web-production-af7ae.up.railway.app/api/health